version: "3.8"

services:
  backend:
    image: uchenna23/backend:latest
    container_name: backend
    ports:
      - "8081:80"  # Exposing backend on host port 8081 (adjust if needed)
    networks:
      - app-network

  frontend:
    image: uchenna23/angular-frontend:latest
    container_name: frontend
    ports:
      - "8080:80"  # Exposing frontend on host port 8080
    environment:
      # Set API_URL to point to the backend service (Docker Compose allows service name resolution)
      - API_URL=http://backend/api
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
