version: "3.8"

services:
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app-network

  backend:
    image: uchenna23/backend:latest
    container_name: backend
    ports:
      - "8081:8081" 
    environment:
      - ALLOWED_ORIGINS=*  # If you're using the env var in your config (or let it be "http://localhost:8080")
      - SPRING_DATA_REDIS_HOST=redis
    networks:
      - app-network

  frontend:
    image: uchenna23/angular-frontend:latest
    container_name: frontend
    ports:
      - "8080:80"
    environment:
      - API_URL=https://crypto-scout-app.azurewebsites.net/api
      - WS_URL=wss://crypto-scout-app.azurewebsites.net/ws
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
