version: "3.8"

services:
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app-network

  backend:
    image: uchenna23/backend:latest
    container_name: backend
    ports:
      - "8081:80"  # Maps backend container's port 80 to host port 8081
    environment:
      - ALLOWED_ORIGINS=*      # For testing, allow all origins
      - SPRING_DATA_REDIS_HOST=redis  # Override Redis host to use the Redis container
    networks:
      - app-network

  frontend:
    image: uchenna23/angular-frontend:latest
    container_name: frontend
    ports:
      - "8080:80"  # Maps frontend container's port 80 to host port 8080
    environment:
      - API_URL=http://backend/api
      - WS_URL=ws://backend/ws
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
